version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindmeld
    volumes:
      - ./.containers/mindmeld:/var/lib/postgresql/data
    ports:
      - "5432:5432"